# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nessie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='venue',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nessie.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventuser',
            name='event_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nessie.Event'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='user_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
