# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nessie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='attendee_Limit',
            new_name='attendee_limit',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_Date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_Date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='event_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='event_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nessie.EventUsers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='event_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nessie.EventUsers'),
            preserve_default=False,
        ),
    ]
