# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nessie', '0002_auto_20160826_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventusers',
            old_name='is_favorite',
            new_name='is_creator',
        ),
    ]
